# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\x12\x04test\"\x1a\n\x07request\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1b\n\x08response\x12\x0f\n\x07message\x18\x01 \x01(\t2?\n\nStreamTest\x12\x31\n\nBothStream\x12\r.test.request\x1a\x0e.test.response\"\x00(\x01\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=20
  _REQUEST._serialized_end=46
  _RESPONSE._serialized_start=48
  _RESPONSE._serialized_end=75
  _STREAMTEST._serialized_start=77
  _STREAMTEST._serialized_end=140
# @@protoc_insertion_point(module_scope)
