# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import test_pb2 as test__pb2


class StreamTestStub(object):
    """服务端和客户端双流
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BothStream = channel.stream_stream(
                '/test.StreamTest/BothStream',
                request_serializer=test__pb2.request.SerializeToString,
                response_deserializer=test__pb2.response.FromString,
                )


class StreamTestServicer(object):
    """服务端和客户端双流
    """

    def BothStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StreamTestServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BothStream': grpc.stream_stream_rpc_method_handler(
                    servicer.BothStream,
                    request_deserializer=test__pb2.request.FromString,
                    response_serializer=test__pb2.response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'test.StreamTest', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StreamTest(object):
    """服务端和客户端双流
    """

    @staticmethod
    def BothStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/test.StreamTest/BothStream',
            test__pb2.request.SerializeToString,
            test__pb2.response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
